// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3REOXtLe9lydAuQNTHwbIhp_-KB2mBI',
    appId: '1:859425649792:web:87115f3bceee1f2e6be265',
    messagingSenderId: '859425649792',
    projectId: 'doctor-dash-app',
    authDomain: 'doctor-dash-app.firebaseapp.com',
    storageBucket: 'doctor-dash-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0bWc8n-qICt1T1PNqctomBgoGcG2nzM',
    appId: '1:859425649792:android:eeb44b7fcdca5d226be265',
    messagingSenderId: '859425649792',
    projectId: 'doctor-dash-app',
    storageBucket: 'doctor-dash-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3IeyvvmTusOpskWXpyvlHvYMYb91y5rI',
    appId: '1:859425649792:ios:6e9740b8c6f97d466be265',
    messagingSenderId: '859425649792',
    projectId: 'doctor-dash-app',
    storageBucket: 'doctor-dash-app.appspot.com',
    iosBundleId: 'com.example.doctorDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3IeyvvmTusOpskWXpyvlHvYMYb91y5rI',
    appId: '1:859425649792:ios:d610377336d345e86be265',
    messagingSenderId: '859425649792',
    projectId: 'doctor-dash-app',
    storageBucket: 'doctor-dash-app.appspot.com',
    iosBundleId: 'com.example.doctorDash.RunnerTests',
  );
}
