// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfU0WpE_SzNHlZawyWBa1iMqzdCfiDDt0',
    appId: '1:124485714686:web:194fba216f1ac3e7251baf',
    messagingSenderId: '124485714686',
    projectId: 'doctor-dash-app-e97f8',
    authDomain: 'doctor-dash-app-e97f8.firebaseapp.com',
    storageBucket: 'doctor-dash-app-e97f8.appspot.com',
    measurementId: 'G-JXYT5V9VS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IU5VAzDpeK-doa-YWX4adkrcQoAQzOc',
    appId: '1:124485714686:android:8aa4924bfb80aad9251baf',
    messagingSenderId: '124485714686',
    projectId: 'doctor-dash-app-e97f8',
    storageBucket: 'doctor-dash-app-e97f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpgXhc0ZU8JnTVJ-jFQnVEZYOoAjmYcE',
    appId: '1:124485714686:ios:0d8121e0c9f959f2251baf',
    messagingSenderId: '124485714686',
    projectId: 'doctor-dash-app-e97f8',
    storageBucket: 'doctor-dash-app-e97f8.appspot.com',
    iosBundleId: 'com.example.doctorDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpgXhc0ZU8JnTVJ-jFQnVEZYOoAjmYcE',
    appId: '1:124485714686:ios:dfbc7edc690169a6251baf',
    messagingSenderId: '124485714686',
    projectId: 'doctor-dash-app-e97f8',
    storageBucket: 'doctor-dash-app-e97f8.appspot.com',
    iosBundleId: 'com.example.doctorDash.RunnerTests',
  );
}
